Log in and checking that the Log in was successful
katenaidich/Autotests pull request #2
Opened 2023-03-23 10:02 UTC by katenaidich

2023-03-23 10:11 UTC, asinka requested changes

2023-03-23 10:11 UTC, asinka commented on tests/loginacademy.spec.ts
> +  await page.goto('https://rahulshettyacademy.com/client')
You can move `https://rahulshettyacademy.com` to the playwright config file to the variable `baseUrl`. It's commented by default. So then you'll be able to call just:
```suggestion
await page.goto('/client')
```

2023-03-23 10:11 UTC, asinka commented on tests/loginacademy.spec.ts
> +  await page.fill('#userEmail', 'kate.naidzich@trak-services.com');
I'm not sure about using work email in public repo. I think you can register and account for non-existent email.

2023-03-23 11:13 UTC, asinka approved these changes

2023-03-24 06:57 UTC, NikitaSemenovV approved these changes

2023-03-24 13:07 UTC, merged